### ISSUE TITLE
Latents as references

### ISSUE THREAD

**Issue by mprzyl** [usnistgov/elft#2]
Hi,
you have recently introduced latent prints as references in your validation tool. The latent print is encoded with frgp of 0 and inserted into the references database along with all the other prints.
During the run of the validation tool this latent found in four of the searches. The respective candidate has a frgp of 0, as it was inserted.
The validation tool stops at this point claiming a frgp of 0 is not allowed.

I am not sure what the expected behavior of our library should be in such cases. Shall we return another frgp?

Could you please clarify this?

**Comment by gfiumara** [comment]
You are handling this correctly. We will remove this check from the validation script in the next few minutes.

In one of the early drafts of ELFT, we were requiring a finger position of 1-10 to be returned, so the validation script checked for that. However, we later decided that we would report accuracy per-finger, per-hand, and per-subject, so _any_ FRGP should be allowed.

**Comment by gfiumara** [comment]
This should be corrected in 011a05c2091d59aa7a2c8f840c853dbfc284aba7. Please re-open this issue if it's not.

Thanks, and please let us know if you suspect anything else is incorrect. Sorry for the trouble!
